### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Haleymiranda79** [Carl-Zhuan-Yuan/Lex-Fridman-Podcast-Chinese-Discussion#1]
atom://teletype/portal/d4efe102-566b-4591-9868-1046dc435e18

**Comment by Carl-Zhuan-Yuan** [comment]
What's this?

**Comment by Carl-Zhuan-Yuan** [comment]
> atom://teletype/portal/d4efe102-566b-4591-9868-1046dc435e18

What's this?
